name: Deploy Images to GHCR

on:
  pull_request:
    branches:
      - develop
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build --no-cache . --tag ghcr.io/karimdevwm/snapface:latest
              docker push ghcr.io/karimdevwm/snapface:latest
          
          - name: Deploy to VPS
            env:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              VPS_HOST: ${{ secrets.VPS_HOST }}
              VPS_USER: ${{ secrets.VPS_USER }}
            run: |
              echo "$SSH_PRIVATE_KEY" > id_rsa
              chmod 600 id_rsa
              ssh -o StrictHostKeyChecking=no -i id_rsa $VPS_USER@$VPS_HOST << 'EOF'
                docker pull your_dockerhub_username/your_image_name:latest
                docker stop your_container_name || true
                docker rm your_container_name || true
                docker run -d --name your_container_name your_dockerhub_username/your_image_name:latest
              EOF
            shell: bash