name: Deploy Images to GHCR

on:
  pull_request:
    branches:
      - develop
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build --no-cache . --tag ghcr.io/karimdevwm/snapface:latest
              docker push ghcr.io/karimdevwm/snapface:latest
          
          - name: Deploy to VPS
            env:
              SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
              VPS_HOST: ${{ secrets.DEPLOY_HOST }}
              VPS_USER: ${{ secrets.DEPLOY_USERNAME }}
            run: |
              echo "$SSH_PRIVATE_KEY" > id_rsa
              chmod 600 id_rsa
              ssh -o StrictHostKeyChecking=no -i id_rsa $DEPLOY_USERNAME@$DEPLOY_HOST << 'EOF'
                docker pull ghcr.io/karimdevwm/snapface:latest
                docker stop snapface-snapFace-1 || true
                docker rm snapface-snapFace-1 || true
                docker run -d --name snapface-snapFace-1 ghcr.io/karimdevwm/snapface:latest
              EOF
            shell: bash