name: Deploy Images to GHCR

#env:
  #DOTNET_VERSION: '8.0.x'

on:
  pull_request:
    branches:
      - develop
jobs:
      push-store-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build --no-cache . --tag ghcr.io/karimdevwm/snapface:latest
              docker push ghcr.io/karimdevwm/snapface:latest
